### PR TITLE
Fix flac sample conversion

### PR DESCRIPTION
**Pull request by panicbit**
Claxon only outputs u32 samples and doesn't scale from the bit depth of the stream to 32 bits. As a result, audrey's sample conversion reduces the volume extremely. This PR tries to work around this problem.

---
This change is [Reviewable](https://reviewable.io/reviews/rustaudio/audrey/25)

### CODE REVIEW

**Comment by panicbit** [comment]
#23 seems to fixe the same issue 😩

**Comment by panicbit** [comment]
#23 uses `sample << (32 - sample_bits)` to shift the samples, but that seems to be not quite right to me. Wouldn't that compress the volume range?

**Comment by est31** [comment]
> Wouldn't that compress the volume range?

How would it compress it? To me it seems that the shift only ensures that the topmost bit of the input data is also the topmost bit of the output data.

**Comment by panicbit** [comment]
I think it's fine. The samples crate does it that way too. Closing this in favor of #23.

**Pull request closed without merging**
